language: python
sudo: false
python:
- '3.5'
- '3.3'
- '3.4'
- '2.7'
- pypy
- pypy3
install:
- pip install coveralls
- pip install codecov
- pip install pep8
script:
- coverage run --source=osmoapi setup.py test
after_success:
- coveralls
- codecov
notifications:
  email:
  - christian.ledermann@gmail.com

